# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gRPC-Server-Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gRPC-Server-Sample
  pod 'SwiftGRPC', '0.4.3'

  target 'gRPC-Server-SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
